FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV SUPABASE_URL=${SUPABASE_URL}
ENV SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
ENV SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
ENV SUPABASE_JWT_SECRET_KEY=${SUPABASE_JWT_SECRET_KEY}
ENV SUPABASE_JWT_ALGORITHM=${SUPABASE_JWT_ALGORITHM}
ENV SUPABASE_JWT_EXPIRATION_TIME=${SUPABASE_JWT_EXPIRATION_TIME}

CMD ["gunicorn", "-w", "1", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]
